version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "<ECS_CONTAINER_NAME>"
          ContainerPort: <ECS_CONTAINER_PORT>
        PlatformVersion: "1.4.0"
